/*
HistoryEntry.kt by Sebastian Grygorczuk
September 2019
sgrygorczuk@gmail.com

This data class defines the structure of the entries that will go into our table
It will have four columns, the input string, the result string that will be
displayed for the user to interact with. And an orientation string which will
be used to determined which rows to display based on which activity layout the
user is looking at. And it will have a primary key which will be autoGenerated.
 */

package com.example.calculator.history

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "history_table")
data class HistoryEntry(
    @ColumnInfo(name = "input") var input: String,
    @ColumnInfo(name = "result") var result: String,
    @ColumnInfo(name = "orientation") var orientation: String){
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
}